### ISSUE TITLE
running docker-up doesn't work

### ISSUE THREAD

**Issue by 4goodapp** [bitnami/bitnami-docker-wordpress-nginx#14]
```
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress-nginx/master/5/debian-9/docker-compose.yml
$ docker-compose up
```

Running the first command download an invalid file.

**Comment by carrodher** [comment]
Hi,

Thanks for reporting the issue, it was an error in the URL. We just moved our containers from Debian 9 to Debian 10, so the directory paths changed from `5/debian-9` to `5/debian-10`.

To avoid this kind of issues [I just updated the README](https://github.com/bitnami/bitnami-docker-wordpress-nginx/commit/6316b297f0a816218efc5922cfe508a1ec258d9b) to use the _docker-compose.yaml_ that appears in the root of the directory that it's the same file than the one present in the `branch/distro` folder.

**Comment by 4goodapp** [comment]
Thanks,

Am still facing a issue. WhenI run `docker-compose up` I get this error message:

```
wordpress_1  | INFO  ==> Starting NGINX...
wordpress_1  | 2020/01/27 13:14:13 [crit] 46#0: pread() "/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf" failed (21: Is a directory)
wordpress_1  | nginx: [crit] pread() "/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf" failed (21: Is a directory)
wordpress_nginx_wordpress_1 exited with code 1

```

**Comment by jkhaui** [comment]
@carrodher you need to update the link in this repo's README, it's still ` curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress-nginx/master/5/debian-9/docker-compose.yml` which is not working

**Comment by carrodher** [comment]
Hi, that is true. I fixed it in this commit (https://github.com/bitnami/bitnami-docker-wordpress-nginx/commit/6316b297f0a816218efc5922cfe508a1ec258d9b) but our automated system overwrites it in this one (https://github.com/bitnami/bitnami-docker-wordpress-nginx/commit/caecce131674e2e9ad95b610b2e317bcf3f84c31). Now I just fixed it in the automated tool, so it should be fixed in the next daily build.

Sorry for the inconvenience.
